server:
  port: 8000
spring:
  cloud:
    config:
      server:
       git:
         default-label: master
         uri: https://github.com/Alexoner03/spring-microservices
         search-paths: config-files
      enabled: true
      name: config-service
  application:
      name: config-service